[package]
name = "ultraman"
version = "0.1.3"
authors = ["yukihirop <te108186@gmail.com>"]
repository = "https://github.com/yukihirop/ultraman"
edition = "2018"
keywords= ["foreman", "multiprocess", "multithread", "pipe"]
categories= ["command-line-utilities"]
license= "MIT"
readme = "README.md"
description = "Manage Procfile-based applications"
exclude = ["example/*", "man/*"]
default-run="ultraman"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
crossbeam-channel = "0.5.0"
dotenv = "0.15.0"
handlebars = "3.5.1"
nix = "0.19.0"
regex = "1.4.2"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
shellwords = "1.1.0"
signal-hook = "0.1.16"
structopt = "0.3.20"
# https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html?highlight=git,version#multiple-locations
roff = { git = "https://github.com/yukihirop/roff-rs", version = ">=0.1.0", optional = true }

[features]
man = [ "roff" ]

[dev-dependencies]
anyhow = "1.0.34"
libc = "0.2.80"
tempfile = "3.1.0"


[[bin]]
name = "ultraman"
path = "src/main.rs"

[[bin]]
name = "man"
path = "man/main.rs"
required-features = [ "man" ]
