# reference: https://github.com/dalance/procs/blob/master/.github/workflows/regression.yml 

name: Regression

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run tests
      run: make test
      shell: bash
      env:
        SHELL: /bin/bash

    - name: Run tests feature variation
      run: make test-no-default-features
      shell: bash
      env:
        SHELL: /bin/bash
