# reference: https://github.com/dalance/procs/blob/master/.github/workflows/release.yml

name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-18.04, macOS-latest, windows-latest]
        os: [ubuntu-18.04, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-18.04'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -qq install musl-tools

    - name: Build for Linux
      if: matrix.os == 'ubuntu-18.04'
      run: make release_linux

    - name: Build for macOS
      if: matrix.os == 'macOS-latest'
      run: make release_mac

    # - name: Build for Windows
    #   if: matrix.os == 'windows-latest'
    #   run: make release_win

    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        files: "*.zip"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
