# reference: https://github.com/dalance/procs/blob/master/.github/workflows/release.yml

name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            make_cmd: release_linux
          - os: macOS-latest
            target: x86_64-apple-darwin
            make_cmd: release_mac
          - os: macOS-latest
            target: aarch64-apple-darwin
            make_cmd: release_mac_arm
          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   make_cmd: release_win

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq musl-tools

    - name: Build release
      run: make ${{ matrix.make_cmd }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with: 
        files: "*.zip"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
